# Generated by Django 5.2.4 on 2025-07-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktask',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='Task due date and time', null=True),
        ),
    ]
