# Generated by Django 5.2.4 on 2025-07-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='google_maps_url',
            field=models.URLField(blank=True, help_text='Google Maps location URL', null=True),
        ),
    ]
