# Generated by Django 5.2.4 on 2025-07-23 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_tenant'),
        ('users', '0002_teammember_teammemberactivity_teammemberperformance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='store',
            field=models.ForeignKey(blank=True, help_text='Store this user belongs to (null for platform/business admins)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='stores.store'),
        ),
    ]
