# Generated by Django 5.2.4 on 2025-07-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_next_follow_up_client_summary_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='summary_notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
