# Generated by Django 4.2.7 on 2025-07-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_make_tenant_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('intent', 'Purchase Intent/Visit Reason'), ('product', 'Product Interest'), ('revenue', 'Revenue-Based'), ('demographic', 'Demographic/Age'), ('source', 'Lead Source'), ('status', 'CRM Status'), ('community', 'Community/Relationship'), ('event', 'Event-Driven'), ('custom', 'Custom')], default='custom', max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer Tag',
                'verbose_name_plural': 'Customer Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='clients', to='clients.customertag'),
        ),
    ]
