# Generated by Django 5.2.4 on 2025-08-04 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_client_status'),
        ('stores', '0002_store_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='store',
            field=models.ForeignKey(blank=True, help_text='Store this customer belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='stores.store'),
        ),
    ]
