# Generated by Django 5.2.4 on 2025-08-05 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0002_store_tenant'),
        ('tenants', '0002_tenant_google_maps_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('email_types', models.JSONField(default=list)),
                ('email_frequency', models.CharField(default='immediate', max_length=20)),
                ('push_enabled', models.BooleanField(default=True)),
                ('push_types', models.JSONField(default=list)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('in_app_types', models.JSONField(default=list)),
                ('in_app_sound', models.BooleanField(default=True)),
                ('in_app_desktop', models.BooleanField(default=True)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('quiet_hours_timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('appointment_reminders', models.BooleanField(default=True)),
                ('deal_updates', models.BooleanField(default=True)),
                ('order_notifications', models.BooleanField(default=True)),
                ('inventory_alerts', models.BooleanField(default=True)),
                ('task_reminders', models.BooleanField(default=True)),
                ('announcements', models.BooleanField(default=True)),
                ('escalations', models.BooleanField(default=True)),
                ('marketing_updates', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_notification_settings', to='tenants.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notification Settings',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('appointment_reminder', 'Appointment Reminder'), ('order_status', 'Order Status'), ('inventory_alert', 'Inventory Alert'), ('new_customer', 'New Customer'), ('deal_update', 'Deal Update'), ('payment_received', 'Payment Received'), ('task_reminder', 'Task Reminder'), ('announcement', 'Announcement'), ('escalation', 'Escalation'), ('marketing_campaign', 'Marketing Campaign')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read')], default='unread', max_length=20)),
                ('action_url', models.CharField(blank=True, max_length=255, null=True)),
                ('action_text', models.CharField(blank=True, max_length=100, null=True)),
                ('is_persistent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_notifications', to='stores.store')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_notifications', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='notificatio_user_id_7088ed_idx'), models.Index(fields=['tenant', 'status'], name='notificatio_tenant__56ab67_idx'), models.Index(fields=['store', 'status'], name='notificatio_store_i_230223_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
    ]
