# Generated by Django 5.2.4 on 2025-08-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('appointment_reminder', 'Appointment Reminder'), ('order_status', 'Order Status'), ('inventory_alert', 'Inventory Alert'), ('new_customer', 'New Customer'), ('deal_update', 'Deal Update'), ('payment_received', 'Payment Received'), ('task_reminder', 'Task Reminder'), ('announcement', 'Announcement'), ('escalation', 'Escalation'), ('marketing_campaign', 'Marketing Campaign'), ('stock_transfer_request', 'Stock Transfer Request'), ('stock_transfer_approved', 'Stock Transfer Approved'), ('stock_transfer_completed', 'Stock Transfer Completed'), ('stock_transfer_cancelled', 'Stock Transfer Cancelled'), ('stock_transfer_rejected', 'Stock Transfer Rejected')], max_length=50),
        ),
    ]
